### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by sinanmut** [Wenchao-M/SAGE#1]
Hi, 
thanks for sharing the code. Results look really good. I actually have a question about the inference time. It is reported in the paper that running time is 0.74ms per frame on NVIDIA RTX3090. Is it that time actually for the Refiner network? or end2end running per frame?

Thanks a lot.

**Comment by Wenchao-M** [comment]
Hi, thanks for your interest in our work. The running time of our model is evaluated by online inferring it on a few motion sequences from the test set. We reported the average per-frame speed here. Please refer to our inference code about this.

**Comment by Wenchao-M** [comment]
You can also refer to [this issue](https://github.com/Wenchao-M/SAGE/issues/3)
