### ISSUE TITLE
前馈次数

### ISSUE THREAD

**Issue by wwwpkol** [Wenchao-M/SAGE#2]
感谢您开源代码。代码中前馈次数为5，两个扩散模型的前馈次数都为5吗？能够提供一下总体网络的 FLOPs，参数量以及前馈一次的FPS？期待您的回复

**Comment by fhan235** [comment]
您好
非常感谢对我们工作的关注
①是的, 两个扩散模型的前馈次数都为5
②由于不同显卡的计算能力间存在差异，我们已经开源了所有代码和权重，为了获得更准确的指标，建议您在自己的机器上进行具体测试与使用
