### ISSUE TITLE
Test with real demo 

### ISSUE THREAD

**Issue by vayneli** [Wenchao-M/SAGE#4]
Thanks for your work. I would like to consult about tests with real data. After using process_quan.py to convert realdata, the test refiner does not seem to run correctly and an error will be reported in TestDataset. What changes need to be made?
 Looking forward to your reply, thanks again.

**Comment by fhan235** [comment]
Hi, thanks for your interest in our work. 
The output of process_quan.py will be something like ***.pt. Usually, it doesn't need to make any changes, you can just specify the location of  ***.pt and run the inference code like this
`
python test_refiner.py --cfg config_decoder/refiner_realdemo.yaml
`
To better address the issue, could you please provide more information about the error?
Let me know if you need any further adjustments!

**Comment by vayneli** [comment]
Thanks for your reply, after getting the output pt file of process_quan, I run the inference code:
python test_refiner.py --cfg config_decoder/refiner_realdemo.yaml,but I get the error like this:
No implementation of “rotation _local_full_gt_list in TestDataset code below:
for i in all_info:
        self.motions.append(i["rotation_local_full_gt_list"]),i also found that the output pt file of process_quan is indeed not include the key, so I would like to confirm whether I need to modify myself

---- Replied Message ----
| From | Han ***@***.***> |
| Date | 08/30/2024 17:10 |
| To | Wenchao-M/SAGE ***@***.***> |
| Cc | vayneli ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Wenchao-M/SAGE] Test with real demo (Issue #4) |

Hi vayneli!
The output of process_quan.py will be something like ***.pt. Usually, it doesn't need to make any changes, you can just specify the location of ***.pt and run the inference code like this
python test_refiner.py --cfg config_decoder/refiner_realdemo.yaml
To better address the issue, could you please provide more information about the error?
Let me know if you need any further adjustments!

**Comment by fhan235** [comment]
Hi, very sorry about that, previously, it was indeed not necessary to make any changes. I just checked the code and it seems that the wrong file version might have been uploaded. If you need it urgently, you can temporarily modify the TestDataset according to the output of process_quan.py. I will fix this issue as soon as possible.

**Comment by vayneli** [comment]
Okay, I get it, very appreciated for your kind reply.

---- Replied Message ----
| From | Han ***@***.***> |
| Date | 08/30/2024 18:36 |
| To | Wenchao-M/SAGE ***@***.***> |
| Cc | vayneli ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Wenchao-M/SAGE] Test with real demo (Issue #4) |

Hi, very sorry about that, previously, it was indeed not necessary to make any changes. I just checked the code and it seems that the wrong file version might have been uploaded. If you need it urgently, you can temporarily modify the TestDataset according to the output of process_quan.py. I will fix this issue as soon as possible.

**Comment by fhan235** [comment]
Hi, to make inference with real data more convenient, I add a new file named [inference_realdemo.py](https://github.com/Wenchao-M/SAGE/blob/main/inference_realdemo.py). You can now simply run python inference_realdemo.py to obtain the full body motion results in the form of a .pkl file. Based on my testing, it is currently producing the correct results.

<img src="https://github.com/user-attachments/assets/a637ce99-719e-4fb7-97e6-8c8777e4bb9b" alt="image" height="200"/>
<img src="https://github.com/user-attachments/assets/9eded55c-02a9-4818-8eee-f0dd8a01d0ad" alt="image" height="200"/>

If you encounter any issues while using it, please feel free to reach out

**Comment by vayneli** [comment]
Okay，I will download and try it, thanks for your kind replay again

---- Replied Message ----
| From | Han ***@***.***> |
| Date | 08/30/2024 22:33 |
| To | Wenchao-M/SAGE ***@***.***> |
| Cc | vayneli ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Wenchao-M/SAGE] Test with real demo (Issue #4) |

Hi, to make inference with real data more convenient, I add a new file named inference_realdemo.py. You can now simply run python inference_realdemo.py to obtain the full body motion results in the form of a .pkl file. Based on my testing, it is currently producing the correct results.

image.png (view on web)image.png (view on web)

If you encounter any issues while using it, please feel free to reach out
