### ISSUE TITLE
About the Loss

### ISSUE THREAD

**Issue by wngTn** [Wenchao-M/SAGE#5]
Hey,

Why do you only take the last frame of each sequence for the loss computation? 
[Code Location](https://github.com/Wenchao-M/SAGE/blob/07415acc6f826c9ed5d58f43f3b47a0e0c49e8c6/train_vqvae.py#L134)

**Comment by Wenchao-M** [comment]
Yes, we only calculate the loss on the last frame as we want our model to be inferred in a sliding window manner.
